let bingoChartInstance = null;

document.getElementById('searchBtn').addEventListener('click', () => {
    const inputName = document.getElementById('usernameInput').value.toLowerCase().trim();
    loadDashboard(inputName);
});

async function loadDashboard(username) {
    const statusDiv = document.getElementById('statusMessage');
    const downloadBtn = document.getElementById('downloadBtn');
    
    statusDiv.innerHTML = 'Loading stats...';
    statusDiv.style.color = '#333';
    if (downloadBtn) downloadBtn.style.display = 'none';

    try {
        // Fetch the database generated by your GitHub Action
        const response = await fetch('data.json');
        if (!response.ok) throw new Error("Database not found.");
        
        const allData = await response.json();

        if (!allData[username]) {
            statusDiv.innerHTML = `User <strong>${username}</strong> is not in the local database.<br><small>Add them to scraper.py and run the GitHub Action.</small>`;
            statusDiv.style.color = '#e67e22';
            return;
        }

        const userData = allData[username];
        
        // Process Bingo races
        const bingoData = userData.races
            .filter(r => r.status === 'finished' && r.goal.name.toLowerCase().includes('bingo'))
            .map(r => {
                // Find the specific entrant matching the searched username
                const entrant = r.entrants.find(e => e.user.name.toLowerCase() === username);
                if (!entrant || !entrant.finish_time) return null;

                return {
                    x: new Date(r.ended_at),
                    y: parseISO8601Duration(entrant.finish_time),
                    goal: r.goal.name
                };
            })
            .filter(d => d !== null)
            .sort((a, b) => a.x - b.x);

        if (bingoData.length === 0) {
            statusDiv.textContent = `No Bingo races found for ${userData.username}.`;
            return;
        }

        // Stats Calculation
        const times = bingoData.map(d => d.y);
        const pb = Math.min(...times);
        const avg = times.reduce((a, b) => a + b, 0) / times.length;

        statusDiv.innerHTML = `
            <div style="font-size: 1.2rem; margin-bottom: 5px;"><strong>${userData.username}</strong></div>
            <div style="font-size: 0.9rem;">
                <span style="color: #27ae60">PB: ${formatSecondsToHHMMSS(pb)}</span> | 
                <span style="color: #3498db">Avg: ${formatSecondsToHHMMSS(avg)}</span> | 
                <span>Races: ${bingoData.length}</span>
            </div>
        `;

        renderChart(bingoData, userData.username);
        if (downloadBtn) downloadBtn.style.display = 'inline-block';

    } catch (error) {
        console.error(error);
        statusDiv.textContent = "Error loading data.json. Make sure the GitHub Action has run successfully.";
        statusDiv.style.color = '#e74c3c';
    }
}

/** * HELPER FUNCTIONS
 */

function parseISO8601Duration(d) {
    const m = d.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:([\d.]+)S)?/);
    return ((parseFloat(m[1])||0)*3600)+((parseFloat(m[2])||0)*60)+(parseFloat(m[3])||0);
}

function formatSecondsToHHMMSS(s) {
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const sec = Math.floor(s % 60);
    return `${h > 0 ? h + ':' : ''}${m.toString().padStart(2, '0')}:${sec.toString().padStart(2, '0')}`;
}

function renderChart(data, name) {
    const ctx = document.getElementById('bingoChart').getContext('2d');
    if (bingoChartInstance) bingoChartInstance.destroy();

    bingoChartInstance = new Chart(ctx, {
        type: 'line',
        data: {
            datasets: [{
                label: 'Bingo Completion Time',
                data: data,
                borderColor: '#3498db',
                backgroundColor: 'rgba(52, 152, 219, 0.1)',
                fill: true,
                tension: 0.3,
                pointRadius: 4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                x: { type: 'time', time: { unit: 'month' } },
                y: { ticks: { callback: v => formatSecondsToHHMMSS(v) } }
            },
            plugins: {
                tooltip: {
                    callbacks: { label: c => `Time: ${formatSecondsToHHMMSS(c.raw.y)} (${c.raw.goal})` }
                }
            }
        }
    });
}